### ISSUE TITLE
Unable to list products based on product Categories

### ISSUE THREAD

**Issue by ebincm** [respinar/contao-products#1]
Haii,

I am using contao-products extension for my product listing. Currently the listing with product catalogue works but unable to list products based on product categories .

**Comment by hamidpeywasti** [comment]
Hi,
Thank you. I'm working on it.

**Comment by ebincm** [comment]
hi @hamidabbaszadeh ,

Thank you for the support. Can I know when will be the new updates available.

**Comment by ebincm** [comment]
Hi @hamidabbaszadeh 
Thank you for the support. Can I know when will be the new updates available.

**Comment by LDI-DAN** [comment]
For installation via the Contao Manager (Contao 4.4.9) gives an error

Using version ^0.16.2 for respinar/contao-products
/var/www/viktor/data/www/1s-uslugi.ru/composer.json has been updated
Loading composer repositories with package information
Updating dependencies
Package operations: 4 installs, 0 updates, 0 removals
  - Installing menatwork/contao-multicolumnwizard (3.3.15): Downloading (100%)
--------------------------------------------------------
Exception occured: Installation target "/var/www/viktor/data/www/1s-uslugi.ru/system/modules/multicolumnwizard" already exists
#0 phar:///var/www/viktor/data/www/1s-uslugi.ru/web/contao-manager.phar.php/vendor/tenside/core/src/Task/Composer/AbstractComposerCommandTask.php(166): Tenside\Core\Task\Composer\AbstractComposerCommandTask->executeCommand(Object(Tenside\Core\Task\Composer\WrappedCommand\RequireCommand), Object(Symfony\Component\Console\Input\ArrayInput), Object(Tenside\Core\Task\TaskOutput))
#1 phar:///var/www/viktor/data/www/1s-uslugi.ru/web/contao-manager.phar.php/vendor/tenside/core/src/Task/Task.php(173): Tenside\Core\Task\Composer\AbstractComposerCommandTask->doPerform()
#2 phar:///var/www/viktor/data/www/1s-uslugi.ru/web/contao-manager.phar.php/vendor/tenside/core/src/Task/Runner.php(89): Tenside\Core\Task\Task->perform('/var/www/viktor...')
#3 phar:///var/www/viktor/data/www/1s-uslugi.ru/web/contao-manager.phar.php/vendor/tenside/core-bundle/src/Command/RunTaskCommand.php(82): Tenside\Core\Task\Runner->run('/var/www/viktor...')
#4 phar:///var/www/viktor/data/www/1s-uslugi.ru/web/contao-manager.phar.php/vendor/symfony/console/Command/Command.php(240): Tenside\CoreBundle\Command\RunTaskCommand->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#5 phar:///var/www/viktor/data/www/1s-uslugi.ru/web/contao-manager.phar.php/vendor/tenside/core-bundle/src/Command/RunTaskCommand.php(61): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#6 phar:///var/www/viktor/data/www/1s-uslugi.ru/web/contao-manager.phar.php/vendor/symfony/console/Application.php(875): Tenside\CoreBundle\Command\RunTaskCommand->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#7 phar:///var/www/viktor/data/www/1s-uslugi.ru/web/contao-manager.phar.php/vendor/symfony/console/Application.php(215): Symfony\Component\Console\Application->doRunCommand(Object(Tenside\CoreBundle\Command\RunTaskCommand), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#8 phar:///var/www/viktor/data/www/1s-uslugi.ru/web/contao-manager.phar.php/api/ApiApplication.php(71): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#9 phar:///var/www/viktor/data/www/1s-uslugi.ru/web/contao-manager.phar.php/vendor/symfony/console/Application.php(122): Contao\ManagerApi\ApiApplication->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#10 phar:///var/www/viktor/data/www/1s-uslugi.ru/web/contao-manager.phar.php/api/console(83): Symfony\Component\Console\Application->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#11 /var/www/viktor/data/www/1s-uslugi.ru/web/contao-manager.phar.php(55): require('phar:///var/www...')
#12 {main}
Chained exception: Installation target "/var/www/viktor/data/www/1s-uslugi.ru/system/modules/multicolumnwizard" already exists
#0 /var/www/viktor/data/www/1s-uslugi.ru/vendor/contao-community-alliance/composer-plugin/src/Installer/AbstractModuleInstaller.php(512): ContaoCommunityAlliance\Composer\Plugin\Installer\AbstractModuleInstaller->canAddTarget('/var/www/viktor...', 3)
#1 /var/www/viktor/data/www/1s-uslugi.ru/vendor/contao-community-alliance/composer-plugin/src/Installer/AbstractModuleInstaller.php(251): ContaoCommunityAlliance\Composer\Plugin\Installer\AbstractModuleInstaller->canAddSymlink('/var/www/viktor...', '/var/www/viktor...', 3)
#2 /var/www/viktor/data/www/1s-uslugi.ru/vendor/contao-community-alliance/composer-plugin/src/Installer/AbstractModuleInstaller.php(116): ContaoCommunityAlliance\Composer\Plugin\Installer\AbstractModuleInstaller->addSymlinks(Object(Composer\Package\CompletePackage), '/var/www/viktor...', Array)
#3 phar:///var/www/viktor/data/www/1s-uslugi.ru/web/contao-manager.phar.php/vendor/composer/composer/src/Composer/Installer/InstallationManager.php(173): ContaoCommunityAlliance\Composer\Plugin\Installer\AbstractModuleInstaller->install(Object(Composer\Repository\InstalledFilesystemRepository), Object(Composer\Package\CompletePackage))
#4 phar:///var/www/viktor/data/www/1s-uslugi.ru/web/contao-manager.phar.php/vendor/composer/composer/src/Composer/Installer/InstallationManager.php(160): Composer\Installer\InstallationManager->install(Object(Composer\Repository\InstalledFilesystemRepository), Object(Composer\DependencyResolver\Operation\InstallOperation))
#5 phar:///var/www/viktor/data/www/1s-uslugi.ru/web/contao-manager.phar.php/vendor/composer/composer/src/Composer/Installer.php(587): Composer\Installer\InstallationManager->execute(Object(Composer\Repository\InstalledFilesystemRepository), Object(Composer\DependencyResolver\Operation\InstallOperation))
#6 phar:///var/www/viktor/data/www/1s-uslugi.ru/web/contao-manager.phar.php/vendor/composer/composer/src/Composer/Installer.php(226): Composer\Installer->doInstall(Object(Composer\Repository\InstalledFilesystemRepository), Object(Composer\Repository\CompositeRepository), Object(Composer\Repository\PlatformRepository), Array)
#7 phar:///var/www/viktor/data/www/1s-uslugi.ru/web/contao-manager.phar.php/vendor/composer/composer/src/Composer/Command/RequireCommand.php(178): Composer\Installer->run()
#8 phar:///var/www/viktor/data/www/1s-uslugi.ru/web/contao-manager.phar.php/vendor/symfony/console/Command/Command.php(240): Composer\Command\RequireCommand->execute(Object(Symfony\Component\Console\Input\ArrayInput), Object(Tenside\Core\Task\TaskOutput))
#9 phar:///var/www/viktor/data/www/1s-uslugi.ru/web/contao-manager.phar.php/vendor/tenside/core/src/Task/Composer/AbstractComposerCommandTask.php(147): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArrayInput), Object(Tenside\Core\Task\TaskOutput))
#10 phar:///var/www/viktor/data/www/1s-uslugi.ru/web/contao-manager.phar.php/vendor/tenside/core/src/Task/Composer/AbstractComposerCommandTask.php(166): Tenside\Core\Task\Composer\AbstractComposerCommandTask->executeCommand(Object(Tenside\Core\Task\Composer\WrappedCommand\RequireCommand), Object(Symfony\Component\Console\Input\ArrayInput), Object(Tenside\Core\Task\TaskOutput))
#11 phar:///var/www/viktor/data/www/1s-uslugi.ru/web/contao-manager.phar.php/vendor/tenside/core/src/Task/Task.php(173): Tenside\Core\Task\Composer\AbstractComposerCommandTask->doPerform()
#12 phar:///var/www/viktor/data/www/1s-uslugi.ru/web/contao-manager.phar.php/vendor/tenside/core/src/Task/Runner.php(89): Tenside\Core\Task\Task->perform('/var/www/viktor...')
#13 phar:///var/www/viktor/data/www/1s-uslugi.ru/web/contao-manager.phar.php/vendor/tenside/core-bundle/src/Command/RunTaskCommand.php(82): Tenside\Core\Task\Runner->run('/var/www/viktor...')
#14 phar:///var/www/viktor/data/www/1s-uslugi.ru/web/contao-manager.phar.php/vendor/symfony/console/Command/Command.php(240): Tenside\CoreBundle\Command\RunTaskCommand->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#15 phar:///var/www/viktor/data/www/1s-uslugi.ru/web/contao-manager.phar.php/vendor/tenside/core-bundle/src/Command/RunTaskCommand.php(61): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#16 phar:///var/www/viktor/data/www/1s-uslugi.ru/web/contao-manager.phar.php/vendor/symfony/console/Application.php(875): Tenside\CoreBundle\Command\RunTaskCommand->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#17 phar:///var/www/viktor/data/www/1s-uslugi.ru/web/contao-manager.phar.php/vendor/symfony/console/Application.php(215): Symfony\Component\Console\Application->doRunCommand(Object(Tenside\CoreBundle\Command\RunTaskCommand), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#18 phar:///var/www/viktor/data/www/1s-uslugi.ru/web/contao-manager.phar.php/api/ApiApplication.php(71): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#19 phar:///var/www/viktor/data/www/1s-uslugi.ru/web/contao-manager.phar.php/vendor/symfony/console/Application.php(122): Contao\ManagerApi\ApiApplication->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#20 phar:///var/www/viktor/data/www/1s-uslugi.ru/web/contao-manager.phar.php/api/console(83): Symfony\Component\Console\Application->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#21 /var/www/viktor/data/www/1s-uslugi.ru/web/contao-manager.phar.php(55): require('phar:///var/www...')
#22 {main}
--------------------------------------------------------


Process terminated with exit code 1
Reason: General error

**Comment by ebincm** [comment]
Haii @hamidabbaszadeh ,

Can I know when will be the new updates available ? .It will be really useful for us if this feature is implemented .We are eagerly waiting for your feedback.

Thank you.

**Comment by hamidpeywasti** [comment]
Hi @ebincm,
I will start working on this extension. That feature will implemeneted ASAP.
Thank you

**Comment by AswathySuresh** [comment]
@hamidabbaszadeh ,
   Any updates on this issue ?

**Comment by hamidpeywasti** [comment]
Hi,
I started maintaining of this extension.

**Comment by oliver-zehentleitner** [comment]
Hello! 

Only including "product" works, but "products" doesnt :/

I keep watching this repo for an update ...

Best regards!

**Comment by hamidpeywasti** [comment]
Hi @oliver-zehentleitner, @AswathySuresh, @ebincm, @LDI-DAN;
Thank you for you comments, 
I just decided to continue developing this Contao Extension as Bundle. Hence there will be new Updates for Contao 4 and 5. I'll add new features.
